config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "about", to: "pages#about"
  get "fullstack", to: "pages#fullstack"
  get "finance", to: "pages#finance"
  get "consulting", to: "pages#consulting"
  resources :contact, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name, validate: true
  attribute :email, validate: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname, captcha: true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      subject: "Contact Form Inquiry",
      to: "daniel.howittcontact@gmail.com",
      from: %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
    @contact = Contact.new(params[:contact])
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    respond_to do |format|
      if @contact.deliver
        # re-initialize contact object for cleared form
        @contact = Contact.new
        format.html { render 'index' }
        format.js   { flash.now[:success] = @message = "Thank you for your message. I'll get back to you soon!" }
      else
        format.html { render 'index' }
        format.js   { flash.now[:error] = @message = "Message did not send." }
      end
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def finance
  end

  def fullstack
  end

  def consulting
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contact/index.html.erb
<div class="contact-banner">
  <%= render 'shared/navbar' %>
  <div class="container">
    <div class="contact-form p-5">
      <%= render 'shared/contact_form' %>
    </div>
  </div>
  <%= render 'shared/footer' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Daniel Howitt</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <% unless current_page?(contact_index_path) %>
    <%= render 'shared/footer' %>
    <% end %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="about-banner">
  <a href="#name"><i class="fas fa-chevron-down"></i></a>
</div>
<div class="container">
  <br>
  <div id="name">
    <h1>Daniel Howitt</h1>
  </div>
  <hr>
  <div class="about-page-content mt-3">
    <div class="about-page-info">
      <h4><strong>Hello !</strong></h4>
      <h5>I'm a full-stack web developer with experience of working in banks, think-tanks and blockchain.</h5>
      <h5>I am passionate about technology's role in innovation which encouraged me to become a full-stack web developer. My aspirations are to be at the forefront of innovation, using technology to improve legacy processes and contribute to disruptive change.</h5>
    </div>
      <div class="about-page-education">
      <h4><strong>Education</strong></h4>
      <div class="education-card">
        <div class="education-le-wagon">
          <h5><strong><%= link_to "Le Wagon", "https://www.lewagon.com/", target: "_blank"%></strong></h5>
          <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png"/>
        </div>
      <h5>Full-stack coding bootcamp</h5>
        <li>Project lead</li>
        <li>Moderated panel talks</li>
      </div>
      <hr>
      <div class="education-card">
        <div class="education-lse d-flex">
          <h5><strong><%= link_to "LSE", "http://www.lse.ac.uk/", target: "_blank" %></strong></h5>
          <img src="https://upload.wikimedia.org/wikipedia/commons/5/51/LSE_Logo.svg"/>
        </div>
        <h5>BSc Management, 2:1 Honours</h5>
        <li>Econometrics Peer Tutor</li>
        <li>Raised > £1,000 for <%= link_to "Student Minds", "https://www.studentminds.org.uk/", target: "_blank"%></li>
        <li>Futsal Team Captain</li>
      </div>
    </div>
    <div class="about-page-experience">
      <h4><strong>Experience</strong></h4>
      <div class="experience-card">
        <h5><strong><%= link_to "Qadre", "https://www.qad.re/", target: "_blank"%></strong> - Finance Associate</h5>
      </div>
        <hr>
      <div class="experience-card">
        <h5><strong><%= link_to "Commerzbank", "https://www.commerzbank.com/", target: "_blank"%></strong> - Credit Risk Intern</h5>
      </div>
        <hr>
      <div class="experience-card">
        <h5><strong><%= link_to "LSE", "http://www.lse.ac.uk/", target: "_blank"%></strong> - Econometrics Peer Tutor</h5>
      </div>
        <hr>
      <div class="experience-card">
        <h5><strong><%= link_to "Z/Yen", "https://www.zyen.com/", target: "_blank"%></strong> - Research Intern</h5>
      </div>
        <hr>
      <div class="experience-card">
        <h5><strong><%= link_to "HSBC", "https://www.hsbc.co.uk/", target: "_blank"%></strong> - Operational Risk Intern</h5>
      </div>
    </div>
  </div>
</div>
  <!-- <br>
  <hr>
  <div class="about-page-experience">
    <h1>Experience</h1>
    <hr>
    <div class="experience-card">
      <h2><%= link_to "Qadre", "https://www.qad.re/", target: "_blank"%></h2>
      <h3>Finance Associate</h3>
      <h4>July 2018 - September 2019</h4>
      <li>Responsible for the financial modelling of projects, analysing internal budgets and building a company wide ROI model.</li>
      <li>Consulted on multiple projects to assess blockchain's compatibility with client businesses.</li>
      <li>Helped design and implement blockchain solutions in the Trade Finance, Post-Trade, FMCG, Recruitment and Corporate Administration industries.</li>
    </div>
    <hr>
    <div class="experience-card"experience-card>
      <h2><%= link_to "Commerzbank AG, Luxembourg", "https://www.commerzbank.com/", target: "_blank"%></h2>
      <h3>Credit Risk Intern</h3>
      <h4>May 2017 - July 2017</h4>
      <li>Led on two major credit reports and three smaller reports, evaluating the credit risk of over €250mn in loans.</li>
      <li>One of the major credit reports was on the division’s largest client - I was commended for my work and presented to the Sub Credit Committee based in Frankfurt.</li>
    </div>
    <hr>
    <div class="experience-card">
      <h2><%= link_to "London School of Economics", "http://www.lse.ac.uk/", target: "_blank"%></h2>
      <h3>Econometrics Peer Tutor</h3>
      <h4>September 2016 - July 2017</h4>
      <li>I met 5 tutees every week to help them with course material and problem sets in preparation for weekly tests and the end of year exam. Each tutee achieved first class grades in the subject.</li>
    </div>
    <hr>
    <div class="experience-card">
      <h2><%= link_to "Z/Yen", "https://www.zyen.com/", target: "_blank"%></h2>
      <h3>Research Intern</h3>
      <h4>May 2016 - June 2016</h4>
      <li>Coordinated a large research project which involved gathering information and analysing data to be included in the final report.</li>
      <li>After completing the project I produced some of my own research on the relationship between accounting practices and pension liabilities and wrote an <%= link_to "article", "https://www.longfinance.net/news/pamphleteers/understanding-the-pension-crisis/", target: "_blank" %> for the company’s blog.</li>
    </div>
    <hr>
    <div class="experience-card">
      <h2><%= link_to "HSBC London", "https://www.hsbc.co.uk/", target: "_blank"%></h2>
      <h3>Operational Risk Intern</h3>
      <h4>June 2014 - July 2014</h4>
      <li>Worked closely with another intern to deliver two presentations to the Chief Risk Officer for Global Banking and Markets and the Operational Risk Management team. We interviewed a number of trading floor staff and risk executives alongside conducting our own research.</li>
      <li>The first presentation was about the causes, consequences, and lessons from the bank’s Deferred Prosecution Agreement and the second was about the drivers and risks around rogue trading in the financial sector.</li>
      <li>After my internship, I spent more time looking into banking culture and subsequently submitted an essay for a school competition, winning a gold prize for my analysis</li>
    </div>
    <hr>
    <div class="experience-card">
      <h2>Other roles</h2>
      <li>F2F salesman for Precision Acquisition (8th December 2016 – January 2017)
      <li>Market research on the property market for a start-up (September – December 2016)</li>
      <li><%= link_to "Prospect Asset Management, Tokyo", "http://prospectjapan.com/pami/", target: "_blank"%> (5th August – 9th August 2013)
      <li><%= link_to "CSFI (Centre for Study of Financial Innovation", "http://www.csfi.org/", target: "_blank"%> (24th June – 5th July 2013)</li>
    </div>
  </div>
</div>
 -->

app/views/pages/consulting.html.erb
<div class="consulting-banner">
  <a href="#service-content"><i class="fas fa-chevron-down"></i></a>
</div>
<div class="container">
  <div class="consulting-content mt-3">
    <div id="service-content">
      <div class="service-header">
        <h2>Consulting</h2>
        <h5><i>Having consulted on multiple projects in retail, real estate, trade finance, post-trade, FMCG, recruitment, sales and corporate administration, I offer different consultancy services depending on your needs.</i></h5>
        <%= link_to "Get in touch", contact_index_path, class: "btn btn-primary" %>
      </div>
      <hr>
      <div class="service-card mt-5">
        <div class="service-title-icon d-flex">
          <i class="fas fa-code-branch"></i>
          <h3>Tech</h3>
        </div>
        <h5>From assessing your UX/UI to recommending system architeture, streamline the design of your web app to complement your business model.</h5>
      </div>
      <div class="service-card mt-5">
        <div class="service-title-icon d-flex">
          <i class="fas fa-chart-bar"></i>
          <h3>Risk</h3>
        </div>
        <h5>Having worked both in operational and credit risk for large scale banks, leverage my experience to detect and mitigate risks.</h5>
      </div>
      <div class="service-card mt-5">
        <div class="service-title-icon d-flex">
          <i class="fas fa-chess-knight"></i>
          <h3>Strategic</h3>
        </div>
        <h5>If you are looking for more general advice, don't hesitate to get in touch and have a preliminary call to see what I can do for you.</h5>
      </div>
    </div>
  </div>
</div>

app/views/pages/finance.html.erb
<div class="finance-banner">
  <i class="fas fa-chevron-down"></i></a>
</div>
<div class="container">
  <div class="finance-content mt-3">
    <div id="service-content">
      <div class="service-header">
        <h2>Financial Analysis & Modelling</h2>
        <h5><i>My background as a finance associate has given me experience to diligently assess operational & credit risk, derive complex financial models and provide strategic insight into the profitability of commercial investments.</i></h5>
        <%= link_to "Get in touch", contact_index_path, class: "btn btn-primary" %>
      </div>
      <hr>
      <div class="service-card mt-5">
        <div class="service-title-icon d-flex">
          <i class="fas fa-balance-scale-left"></i>
          <h3>Analysis</h3>
        </div>
        <h5>Financial analysis constitutes a key part of any strategic decision. Concise financial reporting that assesses the strategic, operational and credit risk of your finance-related transactions offered to ensure compatibility with your budget and long-term business goals. These reports will include both quantitative and qualitative measures that will provide a clear outlook for you to make the best strategic decision.</h5>
      </div>
      <div class="service-card mt-5">
        <div class="service-title-icon d-flex">
          <i class="fas fa-chart-bar"></i>
          <h3>Modelling</h3>
        </div>
        <h5>Dynamic financial modelling services to help you forecast budgeting, growth, and investment opportunities either as an interactive webpage or in Excel format.</h5>
      </div>
    </div>
  </div>
</div>

app/views/pages/fullstack.html.erb
<div class="fullstack-banner">
  <a><i class="fas fa-chevron-down"></i></a>
</div>
<div class="container">
  <div class="fullstack-content mt-3">
    <div id="service-content">
      <div class="service-header">
        <h2>Fullstack Web Development</h2>
        <h5><i>With my full-stack programming skills and acute business acumen, I offer my services from planning to execution and deployment. Maintenance, support and consultancy provided.</i></h5>
        <%= link_to "Get in touch", contact_index_path, class: "btn btn-primary" %>
      </div>
    </div>
    <hr>
    <div class="service-card mt-5">
      <div class="service-title-icon d-flex">
        <i class="fas fa-palette"></i>
        <h3>Front-end design</h3>
      </div>
        <h5>Interactive and thoughtful design thinking is imperative for any business with an online presence. Get in touch to see how I can build or improve the design of your website.</h5>
    </div>
    <div class="service-card mt-5">
      <div class="service-title-icon d-flex">
        <i class="fas fa-layer-group"></i>
        <h3>Enterprise systems</h3>
      </div>
        <h5>Interacting with legacy systems and processes both physical and digital can hinder workflow and cause business-wide inefficiencies. I will work closely with you so that we can assess and map out together an effective enterprise management system for your orders, assets or processes built with a user-friendly interface.</h5>
    </div>
    <div class="service-card mt-5">
      <div class="service-title-icon d-flex">
        <i class="fab fa-sellsy"></i>
        <h3>E-commerce</h3>
      </div>
        <h5>Whether you are an established retailer looking to move online or just starting your boutique retail business, I can build out an end-to-end platform that will resonate with your customer base. Built-in management solutions are implemented that will give you visibility and control in an easy-to-use manner.</h5>
    </div>
    <div class="service-card mt-5">
      <div class="service-title-icon d-flex">
        <i class="fas fa-crosshairs"></i>
        <h3>Industry specific solutions</h3>
      </div>
      <h5>Having built multiple web-apps for my own projects, I can tailor my services to suit your business's specific requirements and take your idea into production.</h5>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner">
  <div class="banner-content ml-4">
    <h1>Welcome</h1>
    <p>Bespoke services tailored to your business needs</p>
    <%= link_to "Get in touch", contact_index_path, class: "btn btn-primary" %>
  </div>
  <a href="#homepage-header"><i class="fas fa-chevron-down"></i></a>
</div>
<div class="homepage-content ml-4 mr-4 mt-2">
  <hr>
  <div id="homepage-header">
    <h1><strong>Services</strong></h1>
  </div>
  <hr>
  <div class="cards mt-3">
    <%= link_to fullstack_path do %>
    <div class="card-category">
      <div class="card-body">
        <h4 class="card-title">Full-stack Web Development</h4>
        <p class="card-text">From webpage design to launching a fully functional web app, I have you covered end-to-end.</p>
        <i class="fas fa-code"></i>
      </div>
    </div>
    <% end %>
    <%= link_to finance_path do %>
    <div class="card-category">
      <div class="card-body">
        <h4 class="card-title">Financial Analysis</h4>
        <p class="card-text">Realise commercial opportunities and meet your growth aspirations with in-depth analysis and insight.</p>
        <i class="fas fa-chart-line"></i>
      </div>
    </div>
    <% end %>
    <%= link_to consulting_path do %>
    <div class="card-category">
      <div class="card-body">
        <h4 class="card-title">Consulting</h4>
        <p class="card-text">Get support on technical processes and financing to help guide strategic decision-making.</p>
        <i class="fas fa-user-tie"></i>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/shared/_contact_form.html.erb
<%= form_for @contact, url: contact_index_path, remote: true do |f| %>
  <div class="contact-name mt-3">
    <%= f.text_field  :name, required: true, class: "contact-form-text-area", placeholder: "Your name" %>
  </div>
  <div class="contact-email mt-3">
    <%= f.text_field :email, required: true, class: "contact-form-text-area", placeholder: "Your email" %>
  </div>
  <div class="contact-message mt-3">
  <%= f.text_area :message, rows: 4, cols: 100, required: true, class: "contact-form-text-area",
                    placeholder: "Send me a message"%>
    <div class= "hidden">
      <%= f.label :nickname %>
      <%= f.text_field :nickname, :hint => 'Leave this field blank!' %>
    </div>
    <div class="contact-submit">
      <%= f.submit 'Send', class: 'btn btn-primary sweet-alert-sent' %>
    </div>
  </div>
<% end %>
<div class="col-md-6" id="flash-message">
  <%= render 'shared/flash' %>
</div>

app/views/shared/_flash.html.erb
<% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer mt-4">
  <div class="footer-links">
    <a href="https://github.com/dfhowitt"><i class="fab fa-github" target="_blank"></i></a>
    <a href="https://www.linkedin.com/in/daniel-howitt-96261810b/" target="_blank"><i class="fab fa-linkedin"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <div class="navbar-left">
    <%= link_to "Home", root_path%>
  </div>
  <div class="navbar-right">
    <%= link_to "About", about_path%>
    <div class="dropdown">
      <button class="dropbtn">Services</button>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink" aria-haspopup="true" aria-expanded="false">
        <%= link_to "Fullstack Web Development", fullstack_path, class: "dropdown-item" %>
        <%= link_to "Financial Analysis & Modelling", finance_path, class: "dropdown-item" %>
        <%= link_to "Consulting", consulting_path, class: "dropdown-item" %>
      </div>
    </div>
    <%= link_to "Contact", contact_index_path%>
  </div>
</div>